; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32-unknown-freebsd -mattr=+y,+zyhybrid < %s | FileCheck %s

define dso_local ptr addrspace(200) @capfromptr(ptr noundef %foo, ptr addrspace(200) noundef %bar) {
; CHECK-LABEL: capfromptr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    bnez a0, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    cmv ca0, cnull
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    scaddr ca0, ca1, a0
; CHECK-NEXT:    ret
entry:
  %0 = ptrtoint ptr %foo to i32
  %1 = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i32(ptr addrspace(200) %bar, i32 %0)
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @llvm.cheri.cap.from.pointer.i32(ptr addrspace(200), i32)
