; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_hybrid_llc < %s \
; RUN:   | FileCheck --check-prefix=RV64LEGACY %s

define dso_local void @captoptr(ptr addrspace(200) noundef %foo) {
; RV64LEGACY-LABEL: captoptr:
; RV64LEGACY:       # %bb.0: # %entry
; RV64LEGACY-NEXT:    ret
entry:
  %0 = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) %foo, ptr addrspace(200) %foo)
  %1 = inttoptr i64 %0 to ptr
  ret void
}

declare i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200), ptr addrspace(200))
