; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc < %s \
; RUN:   | FileCheck --check-prefix=RV32LEGACY %s

define dso_local void @captoptr(ptr addrspace(200) noundef %foo) {
; RV32LEGACY-LABEL: captoptr:
; RV32LEGACY:       # %bb.0: # %entry
; RV32LEGACY-NEXT:    ret
entry:
  %0 = call i32 @llvm.cheri.cap.to.pointer.i32(ptr addrspace(200) %foo, ptr addrspace(200) %foo)
  %1 = inttoptr i32 %0 to ptr
  ret void
}

declare i32 @llvm.cheri.cap.to.pointer.i32(ptr addrspace(200), ptr addrspace(200))
