; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32LEGACY %s

define dso_local ptr @foo(ptr addrspace(200) noundef %cap) {
; RV32LEGACY-LABEL: foo:
; RV32LEGACY:       # %bb.0: # %entry
; RV32LEGACY-NEXT:    mv a0, a0
; RV32LEGACY-NEXT:    ret
entry:
  %0 = call i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) %cap)
  %1 = inttoptr i32 %0 to ptr
  ret ptr %1
}

declare i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200))
