; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_hybrid_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV64LEGACY %s
; RUN: %riscv64y_hybrid_llc -verify-machineinstrs \
; RUN:   -filetype=obj < %s -o /dev/null 2>&1

define i1 @sealed_get(ptr addrspace(200) %cap) nounwind {
; RV64LEGACY-LABEL: sealed_get:
; RV64LEGACY:       # %bb.0:
; RV64LEGACY-NEXT:    gctype a0, ca0
; RV64LEGACY-NEXT:    snez a0, a0
; RV64LEGACY-NEXT:    ret
  %sealed = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) %cap)
  ret i1 %sealed
}

declare i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200))
