; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_hybrid_llc -verify-machineinstrs < %s | FileCheck %s

define i64 @offset_get(ptr addrspace(200) %cap) nounwind {
; CHECK-LABEL: offset_get:
; CHECK:       # %bb.0:
; CHECK-NEXT:    gchi a0, ca0
; CHECK-NEXT:    ret
    %offset = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) %cap)
    ret i64 %offset
}

declare i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200))
