; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32LEGACY %s

define i32 @offset_get(ptr addrspace(200) %cap) nounwind {
; RV32LEGACY-LABEL: offset_get:
; RV32LEGACY:       # %bb.0:
; RV32LEGACY-NEXT:    ybaser a1, ca0
; RV32LEGACY-NEXT:    sub a0, a0, a1
; RV32LEGACY-NEXT:    ret
    %offset = call i32 @llvm.cheri.cap.offset.get.i32(ptr addrspace(200) %cap)
    ret i32 %offset
}
declare i32 @llvm.cheri.cap.offset.get.i32(ptr addrspace(200))
