; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_hybrid_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV64LEGACY %s

define ptr @foo(ptr addrspace(200) %cap) {
; RV64LEGACY-LABEL: foo:
; RV64LEGACY:       # %bb.0: # %entry
; RV64LEGACY-NEXT:    mv a0, a0
; RV64LEGACY-NEXT:    ret
entry:
  %0 = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) %cap)
  %1 = inttoptr i64 %0 to ptr
  ret ptr %1
}

declare i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200))
