; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32PURECAP %s

define dso_local signext i32 @foo(ptr addrspace(200) noundef %cap) addrspace(200) {
; RV32PURECAP-LABEL: foo:
; RV32PURECAP:       # %bb.0: # %entry
; RV32PURECAP-NEXT:    sext.w a0, a0
; RV32PURECAP-NEXT:    ret
entry:
  %0 = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) %cap)
  %conv = trunc i64 %0 to i32
  ret i32 %conv
}

declare i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200)) addrspace(200)
