; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32PURECAP %s

define dso_local i32 @foo(ptr addrspace(200) noundef %cap) addrspace(200) {
; RV32PURECAP-LABEL: foo:
; RV32PURECAP:       # %bb.0: # %entry
; RV32PURECAP-NEXT:    mv a0, a0
; RV32PURECAP-NEXT:    ret
entry:
  %0 = call i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) %cap)
  ret i32 %0
}

declare i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200)) addrspace(200)
