; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc -verify-machineinstrs < %s | FileCheck %s

define i32 @high_get(ptr addrspace(200) %cap) nounwind {
; CHECK-LABEL: high_get:
; CHECK:       # %bb.0:
; CHECK-NEXT:    yhir a0, ca0
; CHECK-NEXT:    ret
    %offset = call i32 @llvm.cheri.cap.high.get.i32(ptr addrspace(200) %cap)
    ret i32 %offset
}
declare i32 @llvm.cheri.cap.high.get.i32(ptr addrspace(200))
