; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc -verify-machineinstrs < %s | FileCheck %s

define ptr addrspace(200) @offset_set(ptr addrspace(200) %cap, i32 %offs) nounwind {
; CHECK-LABEL: offset_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    yhiw ca0, ca0, a1
; CHECK-NEXT:    ret
    %res = call ptr addrspace(200) @llvm.cheri.cap.high.set.i32(ptr addrspace(200) %cap, i32 %offs)
    ret ptr addrspace(200) %res
}
declare ptr addrspace(200) @llvm.cheri.cap.high.set.i32(ptr addrspace(200), i32)
