; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32LEGACY %s

define ptr addrspace(200) @offset_set(ptr addrspace(200) %cap, i32 %offs) nounwind {
; RV32LEGACY-LABEL: offset_set:
; RV32LEGACY:       # %bb.0:
; RV32LEGACY-NEXT:    ybaser a2, ca0
; RV32LEGACY-NEXT:    yaddrw ca0, ca0, a2
; RV32LEGACY-NEXT:    addy ca0, ca0, a1
; RV32LEGACY-NEXT:    ret
    %res = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i32(ptr addrspace(200) %cap, i32 %offs)
    ret ptr addrspace(200) %res
}
declare ptr addrspace(200) @llvm.cheri.cap.offset.set.i32(ptr addrspace(200), i32)
