; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_hybrid_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV64LEGACY %s

define ptr addrspace(200) @offset_set(ptr addrspace(200) %cap, i64 %offs) nounwind {
; RV64LEGACY-LABEL: offset_set:
; RV64LEGACY:       # %bb.0:
; RV64LEGACY-NEXT:    gcbase a2, ca0
; RV64LEGACY-NEXT:    scaddr ca0, ca0, a2
; RV64LEGACY-NEXT:    cadd ca0, ca0, a1
; RV64LEGACY-NEXT:    ret
    %res = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) %cap, i64 %offs)
    ret ptr addrspace(200) %res
}
declare ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200), i64)
