; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV64PURECAP %s

define dso_local signext i32 @capdiff(ptr addrspace(200) noundef %a, ptr addrspace(200) noundef %b) addrspace(200) {
; RV64PURECAP-LABEL: capdiff:
; RV64PURECAP:       # %bb.0: # %entry
; RV64PURECAP-NEXT:    sub a0, a0, a1
; RV64PURECAP-NEXT:    srli a0, a0, 2
; RV64PURECAP-NEXT:    sext.w a0, a0
; RV64PURECAP-NEXT:    ret
entry:
  %0 = call i64 @llvm.cheri.cap.diff.i64(ptr addrspace(200) %a, ptr addrspace(200) %b)
  %1 = lshr exact i64 %0, 2
  %conv = trunc i64 %1 to i32
  ret i32 %conv
}

declare i64 @llvm.cheri.cap.diff.i64(ptr addrspace(200), ptr addrspace(200))
