; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32PURECAP %s

define dso_local i32 @capdiff(ptr addrspace(200) noundef %a, ptr addrspace(200) noundef %b) addrspace(200) {
; RV32PURECAP-LABEL: capdiff:
; RV32PURECAP:       # %bb.0: # %entry
; RV32PURECAP-NEXT:    sub a0, a0, a1
; RV32PURECAP-NEXT:    srai a0, a0, 2
; RV32PURECAP-NEXT:    ret
entry:
  %0 = call i32 @llvm.cheri.cap.diff.i32(ptr addrspace(200) %a, ptr addrspace(200) %b)
  %sub.ptr.div = sdiv exact i32 %0, 4
  ret i32 %sub.ptr.div
}

declare i32 @llvm.cheri.cap.diff.i32(ptr addrspace(200), ptr addrspace(200))
