; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV32PURECAP %s

define dso_local ptr addrspace(200) @inttopointer(i32 %integer) addrspace(200) {
; RV32PURECAP-LABEL: inttopointer:
; RV32PURECAP:       # %bb.0: # %entry
; RV32PURECAP-NEXT:    addy ca0, cnull, a0
; RV32PURECAP-NEXT:    ret
entry:
    %ptr = inttoptr i32 %integer to ptr addrspace(200)
    ret ptr addrspace(200) %ptr
}
