; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv64y_purecap_llc -verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=RV64PURECAP %s

define dso_local ptr addrspace(200) @inttopointer(i64 %integer) addrspace(200) {
; RV64PURECAP-LABEL: inttopointer:
; RV64PURECAP:       # %bb.0: # %entry
; RV64PURECAP-NEXT:    addy ca0, cnull, a0
; RV64PURECAP-NEXT:    ret
entry:
    %ptr = inttoptr i64 %integer to ptr addrspace(200)
    ret ptr addrspace(200) %ptr
}
