; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_hybrid_llc -verify-machineinstrs < %s | FileCheck %s

define dso_local ptr addrspace(200) @inttopointer(i32 %integer) addrspace(200) {
; CHECK-LABEL: inttopointer:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    csrrc ca1, ddc, zero
; CHECK-NEXT:    bnez a0, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    ymv ca0, cnull
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    yaddrw ca0, ca1, a0
; CHECK-NEXT:    ret
entry:
    %ptr = inttoptr i32 %integer to ptr addrspace(200)
    ret ptr addrspace(200) %ptr
}
