; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %riscv32y_purecap_llc < %s \
; RUN:   | FileCheck --check-prefix=RV32PURECAP %s
define dso_local signext i32 @pointertointeger(ptr addrspace(200) noundef %cap) addrspace(200) {
; RV32PURECAP-LABEL: pointertointeger:
; RV32PURECAP:       # %bb.0: # %entry
; RV32PURECAP-NEXT:    mv a0, a0
; RV32PURECAP-NEXT:    ret
entry:
    %ptr.int = ptrtoint ptr addrspace(200) %cap to i32
    ret i32 %ptr.int
}
