; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+y,+cap-mode -target-abi=l64pc128d -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RVY
; RUN: llc -mtriple=riscv64 -mattr=+m,+zba,+y,+cap-mode -target-abi=l64pc128d -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RVY_ZBA

define i8 @adduw(i32 signext %0, ptr addrspace(200) %1) nounwind {
; RVY-LABEL: adduw:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a0, a0, 32
; RVY-NEXT:    srli a0, a0, 32
; RVY-NEXT:    addy ca0, ca1, a0
; RVY-NEXT:    lb a0, 0(ca0)
; RVY-NEXT:    ret
;
; RVY_ZBA-LABEL: adduw:
; RVY_ZBA:       # %bb.0:
; RVY_ZBA-NEXT:    add.uw ca0, a0, ca1
; RVY_ZBA-NEXT:    lb a0, 0(ca0)
; RVY_ZBA-NEXT:    ret
  %3 = zext i32 %0 to i64
  %4 = getelementptr inbounds i8, ptr addrspace(200) %1, i64 %3
  %5 = load i8, ptr addrspace(200) %4
  ret i8 %5
}

define signext i16 @sh1adduw(i32 signext %0, ptr addrspace(200) %1){
; RVY-LABEL: sh1adduw:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a0, a0, 32
; RVY-NEXT:    srli a0, a0, 31
; RVY-NEXT:    addy ca0, ca1, a0
; RVY-NEXT:    lh a0, 0(ca0)
; RVY-NEXT:    ret
;
; RVY_ZBA-LABEL: sh1adduw:
; RVY_ZBA:       # %bb.0:
; RVY_ZBA-NEXT:    sh1add.uw ca0, a0, ca1
; RVY_ZBA-NEXT:    lh a0, 0(ca0)
; RVY_ZBA-NEXT:    ret
    %3 = zext i32 %0 to i64
    %4 = getelementptr inbounds i16, ptr addrspace(200) %1, i64 %3
    %5 = load i16, ptr addrspace(200) %4
    ret i16 %5
}


define signext i32 @sh2adduw(i32 signext %0, ptr addrspace(200) %1) {
; RVY-LABEL: sh2adduw:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a0, a0, 32
; RVY-NEXT:    srli a0, a0, 30
; RVY-NEXT:    addy ca0, ca1, a0
; RVY-NEXT:    lw a0, 0(ca0)
; RVY-NEXT:    ret
;
; RVY_ZBA-LABEL: sh2adduw:
; RVY_ZBA:       # %bb.0:
; RVY_ZBA-NEXT:    sh2add.uw ca0, a0, ca1
; RVY_ZBA-NEXT:    lw a0, 0(ca0)
; RVY_ZBA-NEXT:    ret
  %3 = zext i32 %0 to i64
  %4 = getelementptr inbounds i32, ptr addrspace(200) %1, i64 %3
  %5 = load i32, ptr addrspace(200) %4
  ret i32 %5
}

define i64 @sh3adduw(i32 signext %0, ptr addrspace(200) %1) {
; RVY-LABEL: sh3adduw:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a0, a0, 32
; RVY-NEXT:    srli a0, a0, 29
; RVY-NEXT:    addy ca0, ca1, a0
; RVY-NEXT:    ld a0, 0(ca0)
; RVY-NEXT:    ret
;
; RVY_ZBA-LABEL: sh3adduw:
; RVY_ZBA:       # %bb.0:
; RVY_ZBA-NEXT:    sh3add.uw ca0, a0, ca1
; RVY_ZBA-NEXT:    ld a0, 0(ca0)
; RVY_ZBA-NEXT:    ret
  %3 = zext i32 %0 to i64
  %4 = getelementptr inbounds i64, ptr addrspace(200) %1, i64 %3
  %5 = load i64, ptr addrspace(200) %4
  ret i64 %5
}

define i64 @adduw_2(i64 %a, i64 %b) nounwind {
; RVY-LABEL: adduw_2:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a1, a1, 32
; RVY-NEXT:    srli a1, a1, 32
; RVY-NEXT:    add a0, a1, a0
; RVY-NEXT:    ret
;
; RVY_ZBA-LABEL: adduw_2:
; RVY_ZBA:       # %bb.0:
; RVY_ZBA-NEXT:    add.uw ca1, a1, cnull
; RVY_ZBA-NEXT:    add a0, a1, a0
; RVY_ZBA-NEXT:    ret
  %and = and i64 %b, 4294967295
  %add = add i64 %and, %a
  ret i64 %add
}
