; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+m,+y,+cap-mode -target-abi=l64pc128d -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RVY
; RUN: llc -mtriple=riscv64 -mattr=+m,+zish4add,+y,+cap-mode -target-abi=l64pc128d -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=ZISH4A

define ptr addrspace(200) @sh4add(i64 %0, ptr addrspace(200) %1){
; RVY-LABEL: sh4add:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a0, a0, 4
; RVY-NEXT:    addy ca0, ca1, a0
; RVY-NEXT:    ly ca0, 0(ca0)
; RVY-NEXT:    ret
;
; ZISH4A-LABEL: sh4add:
; ZISH4A:       # %bb.0:
; ZISH4A-NEXT:    sh4add ca0, a0, ca1
; ZISH4A-NEXT:    ly ca0, 0(ca0)
; ZISH4A-NEXT:    ret
    %3 = getelementptr inbounds ptr addrspace(200), ptr addrspace(200) %1, i64 %0
    %4 = load ptr addrspace(200), ptr addrspace(200) %3
    ret ptr addrspace(200) %4
}

define signext i64 @sh4add_mult(i64 %0, i64 %1){
; RVY-LABEL: sh4add_mult:
; RVY:       # %bb.0:
; RVY-NEXT:    slli a0, a0, 4
; RVY-NEXT:    add a0, a0, a1
; RVY-NEXT:    ret
;
; ZISH4A-LABEL: sh4add_mult:
; ZISH4A:       # %bb.0:
; ZISH4A-NEXT:    # kill: def $x11 killed $x11 def $c11
; ZISH4A-NEXT:    sh4add ca0, a0, ca1
; ZISH4A-NEXT:    # kill: def $x10 killed $x10 killed $c10
; ZISH4A-NEXT:    ret
  %a = shl i64 %0, 4
  %b = add i64 %a, %1
  ret i64 %b
}

define i64 @addmul272(i64 %a, i64 %b) {
; RVY-LABEL: addmul272:
; RVY:       # %bb.0:
; RVY-NEXT:    li a2, 272
; RVY-NEXT:    mul a0, a0, a2
; RVY-NEXT:    add a0, a0, a1
; RVY-NEXT:    ret
;
; ZISH4A-LABEL: addmul272:
; ZISH4A:       # %bb.0:
; ZISH4A-NEXT:    # kill: def $x11 killed $x11 def $c11
; ZISH4A-NEXT:    sh4add ca0, a0, ca1
; ZISH4A-NEXT:    sh4add ca0, a0, ca1
; ZISH4A-NEXT:    # kill: def $x10 killed $x10 killed $c10
; ZISH4A-NEXT:    ret
  %c = mul i64 %a, 272
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul272_ptr(i64 %a, ptr addrspace(200) %b){
; RVY-LABEL: addmul272_ptr:
; RVY:       # %bb.0:
; RVY-NEXT:    li a2, 272
; RVY-NEXT:    mul a0, a0, a2
; RVY-NEXT:    addy ca0, ca1, a0
; RVY-NEXT:    ld a0, 0(ca0)
; RVY-NEXT:    ret
;
; ZISH4A-LABEL: addmul272_ptr:
; ZISH4A:       # %bb.0:
; ZISH4A-NEXT:    # kill: def $x10 killed $x10 def $c10
; ZISH4A-NEXT:    sh4add ca0, a0, ca0
; ZISH4A-NEXT:    sh4add ca0, a0, ca1
; ZISH4A-NEXT:    ld a0, 0(ca0)
; ZISH4A-NEXT:    ret
  %c = mul i64 %a, 272
  %d = getelementptr inbounds i8, ptr addrspace(200) %b, i64 %c
  %e = load i64, ptr addrspace(200) %d
  ret i64 %e
}
