; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %cheri_purecap_llc %s -o - | FileCheck %s

; Function Attrs: norecurse nounwind memory(none)
define ptr addrspace(200) @imm(ptr addrspace(200) readnone %a) local_unnamed_addr #0 {
; CHECK-LABEL: imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cincoffset $c3, $c3, 1023
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 1023
  ret ptr addrspace(200) %add.ptr
}

; Function Attrs: norecurse nounwind memory(none)
define ptr addrspace(200) @imm1(ptr addrspace(200) readnone %a) local_unnamed_addr #0 {
; CHECK-LABEL: imm1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cincoffset $c3, $c3, -1024
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -1024
  ret ptr addrspace(200) %add.ptr
}

; Function Attrs: norecurse nounwind memory(none)
define ptr addrspace(200) @reg(ptr addrspace(200) readnone %a) local_unnamed_addr #0 {
; CHECK-LABEL: reg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    daddiu $1, $zero, 1024
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cincoffset $c3, $c3, $1
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 1024
  ret ptr addrspace(200) %add.ptr
}

; Function Attrs: norecurse nounwind memory(none)
define ptr addrspace(200) @reg1(ptr addrspace(200) readnone %a) local_unnamed_addr #0 {
; CHECK-LABEL: reg1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    daddiu $1, $zero, -1025
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cincoffset $c3, $c3, $1
entry:
  %add.ptr = getelementptr inbounds i8, ptr addrspace(200) %a, i64 -1025
  ret ptr addrspace(200) %add.ptr
}

attributes #0 = { norecurse nounwind memory(none) }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"PIC Level", i32 2}
!2 = !{!"clang version 5.0.0 "}
