; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %cheri_purecap_llc -O1 %s -o - -disable-mips-delay-filler | FileCheck %s

%struct.name_t = type { ptr addrspace(200) }

@x = common local_unnamed_addr addrspace(200) global %struct.name_t zeroinitializer, align 16

define void @test(ptr addrspace(200) %str) local_unnamed_addr {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; CHECK-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; CHECK-NEXT:    cgetpccincoffset $c1, $1
; CHECK-NEXT:    clcbi $c1, %captab20(x)($c1)
; CHECK-NEXT:    clc $c2, $zero, 0($c1)
; CHECK-NEXT:    csc $c2, $zero, 0($c3)
; CHECK-NEXT:    clw $1, $zero, 24($c1)
; CHECK-NEXT:    csw $1, $zero, 24($c3)
; CHECK-NEXT:    cld $1, $zero, 16($c1)
; CHECK-NEXT:    csd $1, $zero, 16($c3)
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    nop
; CHERI256 couldn't do a capability copy here, instead it used two 8-byte ones
entry:
  %0 = bitcast ptr addrspace(200) %str to ptr addrspace(200)
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %0, ptr addrspace(200) align 16 @x, i64 28, i1 false)
  ret void
}

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly, ptr addrspace(200) noalias nocapture readonly, i64, i1 immarg) #0

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
