; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple riscv64 -mattr=+xcheri -target-abi l64pc128 -pre-isel-intrinsic-lowering -mem-intrinsic-expand-size=0 -o - %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n32:64-S128-A200-P200-G200"

define void @foo(ptr addrspace(200) %a, ptr addrspace(200) %b, i64 %n) addrspace(200) #0 {
; CHECK-LABEL: define void @foo
; CHECK-SAME: (ptr addrspace(200) [[A:%.*]], ptr addrspace(200) [[B:%.*]], i64 [[N:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    br label [[HEAD_START:%.*]]
; CHECK:       head.start:
; CHECK-NEXT:    [[SRC_ADDR:%.*]] = ptrtoint ptr addrspace(200) [[B]] to i64
; CHECK-NEXT:    [[REM_ADDR:%.*]] = and i64 [[SRC_ADDR]], 15
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i64 [[REM_ADDR]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ne i64 [[N]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = and i1 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    br i1 [[TMP3]], label [[HEAD_LOOP:%.*]], label [[BODY_START:%.*]]
; CHECK:       head.loop:
; CHECK-NEXT:    [[TMP4:%.*]] = phi ptr addrspace(200) [ [[B]], [[HEAD_START]] ], [ [[TMP7:%.*]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = phi ptr addrspace(200) [ [[A]], [[HEAD_START]] ], [ [[TMP9:%.*]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = phi i64 [ [[N]], [[HEAD_START]] ], [ [[DEC:%.*]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP7]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP4]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr addrspace(200) [[TMP4]], align 1
; CHECK-NEXT:    [[TMP9]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP5]], i64 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr addrspace(200) [[TMP5]], align 1
; CHECK-NEXT:    [[DEC]] = sub i64 [[TMP6]], 1
; CHECK-NEXT:    [[SRC_ADDR1:%.*]] = ptrtoint ptr addrspace(200) [[TMP7]] to i64
; CHECK-NEXT:    [[REM_ADDR2:%.*]] = and i64 [[SRC_ADDR1]], 15
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i64 [[REM_ADDR2]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ne i64 [[DEC]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = and i1 [[TMP10]], [[TMP11]]
; CHECK-NEXT:    br i1 [[TMP12]], label [[HEAD_LOOP]], label [[BODY_START]]
; CHECK:       body.start:
; CHECK-NEXT:    [[TMP13:%.*]] = phi ptr addrspace(200) [ [[B]], [[HEAD_START]] ], [ [[TMP7]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP14:%.*]] = phi ptr addrspace(200) [ [[A]], [[HEAD_START]] ], [ [[TMP9]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP15:%.*]] = phi i64 [ [[N]], [[HEAD_START]] ], [ [[DEC]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[DST_ADDR:%.*]] = ptrtoint ptr addrspace(200) [[TMP14]] to i64
; CHECK-NEXT:    [[REM_ADDR3:%.*]] = and i64 [[DST_ADDR]], 15
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[REM_ADDR3]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = icmp ugt i64 [[TMP15]], 15
; CHECK-NEXT:    [[TMP18:%.*]] = select i1 [[TMP16]], i1 [[TMP17]], i1 false
; CHECK-NEXT:    br i1 [[TMP18]], label [[BODY_LOOP:%.*]], label [[TAIL_START:%.*]]
; CHECK:       body.loop:
; CHECK-NEXT:    [[TMP19:%.*]] = phi ptr addrspace(200) [ [[TMP13]], [[BODY_START]] ], [ [[TMP23:%.*]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = phi ptr addrspace(200) [ [[TMP14]], [[BODY_START]] ], [ [[TMP24:%.*]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP21:%.*]] = phi i64 [ [[TMP15]], [[BODY_START]] ], [ [[TMP25:%.*]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[TMP19]], align 16
; CHECK-NEXT:    [[TMP23]] = getelementptr inbounds ptr addrspace(200), ptr addrspace(200) [[TMP19]], i64 1
; CHECK-NEXT:    store ptr addrspace(200) [[TMP22]], ptr addrspace(200) [[TMP20]], align 16
; CHECK-NEXT:    [[TMP24]] = getelementptr inbounds ptr addrspace(200), ptr addrspace(200) [[A]], i64 1
; CHECK-NEXT:    [[TMP25]] = sub i64 [[TMP21]], 16
; CHECK-NEXT:    [[TMP26:%.*]] = icmp ugt i64 [[TMP25]], 15
; CHECK-NEXT:    br i1 [[TMP26]], label [[BODY_LOOP]], label [[TAIL_START]]
; CHECK:       tail.start:
; CHECK-NEXT:    [[TMP27:%.*]] = phi ptr addrspace(200) [ [[TMP13]], [[BODY_START]] ], [ [[TMP23]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP28:%.*]] = phi ptr addrspace(200) [ [[TMP14]], [[BODY_START]] ], [ [[TMP24]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP29:%.*]] = phi i64 [ [[TMP15]], [[BODY_START]] ], [ [[TMP25]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP30:%.*]] = icmp ugt i64 [[TMP29]], 0
; CHECK-NEXT:    br i1 [[TMP30]], label [[TAIL_LOOP:%.*]], label [[MEMCPY_SPLIT:%.*]]
; CHECK:       tail.loop:
; CHECK-NEXT:    [[TMP31:%.*]] = phi ptr addrspace(200) [ [[TMP27]], [[TAIL_START]] ], [ [[TMP34:%.*]], [[TAIL_LOOP]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = phi ptr addrspace(200) [ [[TMP28]], [[TAIL_START]] ], [ [[TMP35:%.*]], [[TAIL_LOOP]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = phi i64 [ [[TMP29]], [[TAIL_START]] ], [ [[TMP36:%.*]], [[TAIL_LOOP]] ]
; CHECK-NEXT:    [[TMP34]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP31]], i64 1
; CHECK-NEXT:    [[TMP35]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP32]], i64 1
; CHECK-NEXT:    [[TMP36]] = sub i64 [[TMP33]], 1
; CHECK-NEXT:    [[TMP37:%.*]] = load i8, ptr addrspace(200) [[TMP31]], align 1
; CHECK-NEXT:    store i8 [[TMP37]], ptr addrspace(200) [[TMP35]], align 1
; CHECK-NEXT:    [[TMP38:%.*]] = icmp ugt i64 [[TMP36]], 0
; CHECK-NEXT:    br i1 [[TMP38]], label [[TAIL_LOOP]], label [[MEMCPY_SPLIT]]
; CHECK:       memcpy-split:
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) %a, ptr addrspace(200) %b, i64 %n, i1 false)
  ret void
}

define void @call_memcpy(ptr addrspace(200) align 16 %dst, ptr addrspace(200) align 16 %src) #0 {
; CHECK-LABEL: define void @call_memcpy
; CHECK-SAME: (ptr addrspace(200) align 16 [[DST:%.*]], ptr addrspace(200) align 16 [[SRC:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[HEAD_START:%.*]]
; CHECK:       head.start:
; CHECK-NEXT:    [[SRC_ADDR:%.*]] = ptrtoint ptr addrspace(200) [[SRC]] to i64
; CHECK-NEXT:    [[REM_ADDR:%.*]] = and i64 [[SRC_ADDR]], 15
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ne i64 [[REM_ADDR]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = and i1 [[TMP0]], true
; CHECK-NEXT:    br i1 [[TMP1]], label [[HEAD_LOOP:%.*]], label [[BODY_START:%.*]]
; CHECK:       head.loop:
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr addrspace(200) [ [[SRC]], [[HEAD_START]] ], [ [[TMP5:%.*]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = phi ptr addrspace(200) [ [[DST]], [[HEAD_START]] ], [ [[TMP7:%.*]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ 40, [[HEAD_START]] ], [ [[DEC:%.*]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP5]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP2]], i64 1
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr addrspace(200) [[TMP2]], align 1
; CHECK-NEXT:    [[TMP7]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP3]], i64 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr addrspace(200) [[TMP3]], align 1
; CHECK-NEXT:    [[DEC]] = sub i64 [[TMP4]], 1
; CHECK-NEXT:    [[SRC_ADDR1:%.*]] = ptrtoint ptr addrspace(200) [[TMP5]] to i64
; CHECK-NEXT:    [[REM_ADDR2:%.*]] = and i64 [[SRC_ADDR1]], 15
; CHECK-NEXT:    [[TMP8:%.*]] = icmp ne i64 [[REM_ADDR2]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ne i64 [[DEC]], 0
; CHECK-NEXT:    [[TMP10:%.*]] = and i1 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[HEAD_LOOP]], label [[BODY_START]]
; CHECK:       body.start:
; CHECK-NEXT:    [[TMP11:%.*]] = phi ptr addrspace(200) [ [[SRC]], [[HEAD_START]] ], [ [[TMP5]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = phi ptr addrspace(200) [ [[DST]], [[HEAD_START]] ], [ [[TMP7]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = phi i64 [ 40, [[HEAD_START]] ], [ [[DEC]], [[HEAD_LOOP]] ]
; CHECK-NEXT:    [[DST_ADDR:%.*]] = ptrtoint ptr addrspace(200) [[TMP12]] to i64
; CHECK-NEXT:    [[REM_ADDR3:%.*]] = and i64 [[DST_ADDR]], 15
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[REM_ADDR3]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = icmp ugt i64 [[TMP13]], 15
; CHECK-NEXT:    [[TMP16:%.*]] = select i1 [[TMP14]], i1 [[TMP15]], i1 false
; CHECK-NEXT:    br i1 [[TMP16]], label [[BODY_LOOP:%.*]], label [[TAIL_START:%.*]]
; CHECK:       body.loop:
; CHECK-NEXT:    [[TMP17:%.*]] = phi ptr addrspace(200) [ [[TMP11]], [[BODY_START]] ], [ [[TMP21:%.*]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = phi ptr addrspace(200) [ [[TMP12]], [[BODY_START]] ], [ [[TMP22:%.*]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP19:%.*]] = phi i64 [ [[TMP13]], [[BODY_START]] ], [ [[TMP23:%.*]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[TMP17]], align 16
; CHECK-NEXT:    [[TMP21]] = getelementptr inbounds ptr addrspace(200), ptr addrspace(200) [[TMP17]], i64 1
; CHECK-NEXT:    store ptr addrspace(200) [[TMP20]], ptr addrspace(200) [[TMP18]], align 16
; CHECK-NEXT:    [[TMP22]] = getelementptr inbounds ptr addrspace(200), ptr addrspace(200) [[DST]], i64 1
; CHECK-NEXT:    [[TMP23]] = sub i64 [[TMP19]], 16
; CHECK-NEXT:    [[TMP24:%.*]] = icmp ugt i64 [[TMP23]], 15
; CHECK-NEXT:    br i1 [[TMP24]], label [[BODY_LOOP]], label [[TAIL_START]]
; CHECK:       tail.start:
; CHECK-NEXT:    [[TMP25:%.*]] = phi ptr addrspace(200) [ [[TMP11]], [[BODY_START]] ], [ [[TMP21]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = phi ptr addrspace(200) [ [[TMP12]], [[BODY_START]] ], [ [[TMP22]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP27:%.*]] = phi i64 [ [[TMP13]], [[BODY_START]] ], [ [[TMP23]], [[BODY_LOOP]] ]
; CHECK-NEXT:    [[TMP28:%.*]] = icmp ugt i64 [[TMP27]], 0
; CHECK-NEXT:    br i1 [[TMP28]], label [[TAIL_LOOP:%.*]], label [[MEMCPY_SPLIT:%.*]]
; CHECK:       tail.loop:
; CHECK-NEXT:    [[TMP29:%.*]] = phi ptr addrspace(200) [ [[TMP25]], [[TAIL_START]] ], [ [[TMP32:%.*]], [[TAIL_LOOP]] ]
; CHECK-NEXT:    [[TMP30:%.*]] = phi ptr addrspace(200) [ [[TMP26]], [[TAIL_START]] ], [ [[TMP33:%.*]], [[TAIL_LOOP]] ]
; CHECK-NEXT:    [[TMP31:%.*]] = phi i64 [ [[TMP27]], [[TAIL_START]] ], [ [[TMP34:%.*]], [[TAIL_LOOP]] ]
; CHECK-NEXT:    [[TMP32]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP29]], i64 1
; CHECK-NEXT:    [[TMP33]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP30]], i64 1
; CHECK-NEXT:    [[TMP34]] = sub i64 [[TMP31]], 1
; CHECK-NEXT:    [[TMP35:%.*]] = load i8, ptr addrspace(200) [[TMP29]], align 1
; CHECK-NEXT:    store i8 [[TMP35]], ptr addrspace(200) [[TMP33]], align 1
; CHECK-NEXT:    [[TMP36:%.*]] = icmp ugt i64 [[TMP34]], 0
; CHECK-NEXT:    br i1 [[TMP36]], label [[TAIL_LOOP]], label [[MEMCPY_SPLIT]]
; CHECK:       memcpy-split:
; CHECK-NEXT:    ret void
;
entry:
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %dst, ptr addrspace(200) align 16 %src, i64 40, i1 false)
  ret void
}
declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly, ptr addrspace(200) noalias nocapture readonly, i64, i1 immarg)

attributes #0 = { nounwind "no-builtins" }
